services:
  - type: web
    name: voc-report-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
